version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: development
    command:
      - "npm"
      - "run"
      - "start"
    environment:
      NODE_ENV: "development"
    env_file:
      - ".env"
    volumes:
      - ./:/app:rw
    networks:
      - eve-storage

networks:
  eve-storage:
    external: true
